SELECT * FROM EMP 
WHERE EMPNO = 7782;

SELECT ENAME, UPPER(ENAME),LOWER(ENAME),INITCAP(ENAME)
FROM EMP;

SELECT * FROM EMP
WHERE UPPER(ENAME) = UPPER('SCOTT');

SELECT * FROM EMP
WHERE UPPER(ENAME) LIKE UPPER('%scott%');


SELECT UPPER(ENAME) FROM EMP;

SELECT ENAME, LENGTH(ENAME) FROM EMP;

SELECT ENAME, LENGTH(ENAME) FROM EMP
WHERE LENGTH(ENAME) >= 5;

SELECT LENGTH('한글'), LENGTHB('한글')
FROM DUAL;

SELECT * FROM EMP
WHERE LENGTH(JOB) >= 5;

SELECT JOB, SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5) FROM EMP;